### ISSUE TITLE
A few more examples on how to use the API

### ISSUE THREAD

**Issue by S-North** [kakaroto/fvtt-module-api#7] opened 2024-05-31 08:27 UTC
Hi, I've set this up in foundry and am able to get a respone for your example https://example.com/modules/api/api.html?name=world
I'm confused ablout how to access other data or send other requests. This is almost certainly due to a lack of knowledge about the Foundry API on my part.
I wonder if you might be able to provide some more illustrative examples in the readme. My experience of accessing the Foundry API is via the browser console e.g. game.user to get the current logged in user, game.actors.getName("some name"), canvas.tokens.controlled, etc.
When I try https://example.com/modules/api/api.html?name=game or https://example.com/modules/api/api.html?name=canvas.tokens.controlled I get no response. Not even an error.

I would be grateful if you could let me know how I am going wrong and maybe provide a bit of guidance for people like me who are confused.

Many thanks

**Comment by S-North** [comment] 2024-05-31 10:16
I just found a previous requst along the same lines https://github.com/kakaroto/fvtt-module-api/issues/2
From this I understand that the API being referenced is the undoccumented raw websocket API. The previous suggestion was to look at the websocket traffic in the network tab of the browser. I'm starting to go down the rabit hole now.

When I select a new token, there are like a hundred WS request e.g. 

```
{
	"data": [
		"modifyDocument",
		{
			"action": "get",
			"type": "Item",
			"query": {
				"_id__in": [
					"XMcnh4cSI32tljXa",
					"BlAOM2X92SI6HMtJ"
				]
			},
			"options": {
				"index": false,
				"broadcast": false
			},
			"pack": "pf2e.actionspf2e"
		}
	]
}
```
Which I'm guessing is requesting the tokens actions. But when I try and replicate this request in for the API like this I get nothing
/modules/api/api.html?name=modifyDocument&arg0={"1":"action":"get","type":"Item","query":"_id__in":"XMcnh4cSI32tljXa","BlAOM2X92SI6HMtJ"]},"options":"index":false,"broadcast":false},"pack":"pf2e.actionspf2e"}}

Is this an encoding issue or something else I'm geting wrong?

**Comment by kakaroto** [comment] 2024-06-10 23:42
> I would be grateful if you could let me know how I am going wrong and maybe provide a bit of guidance for people like me who are confused.

Hi,
I think the main confusion here is that this gives access to Foundry's **websocket API**, not it's client-side javascript API. 
I see you've already found that out and went down that rabbit hole.


> /modules/api/api.html?name=modifyDocument&arg0={"1":"action":"get","type":"Item","query":"_id__in":"XMcnh4cSI32tljXa","BlAOM2X92SI6HMtJ"]},"options":"index":false,"broadcast":false},"pack":"pf2e.actionspf2e"}}
> 
> Is this an encoding issue or something else I'm geting wrong?

The issue I see in that one is that it's a malformed json object, see the very beginning of the arg0, you put `{"1":"action":"get"` the `"1":` is extra and makes the json invalid.
I'd recommend checking against something like https://jsonlint.com/ or https://jsonformatter.curiousconcept.com/

Trying it now:
![image](https://github.com/kakaroto/fvtt-module-api/assets/27990/10464d55-ff07-411a-9fbb-5c49de6c9c03)
I see you also have a missing `{` after `query`, missing a `[` after the `_id_in` so you have a closing array which was never opened for example. Also a missing `{` after `options` and you have an extra `}` at the end.

And yeah, that query seems to be used to retrieved an item from a compendium pack. 
This however works: `api.html?name=modifyDocument&arg0={"action":"get","type":"Item","query":{"_id__in":["XMcnh4cSI32tljXa","BlAOM2X92SI6HMtJ"]},"options":{"index":false,"broadcast":false},"pack":"pf2e.actionspf2e"}`

![image](https://github.com/kakaroto/fvtt-module-api/assets/27990/f2ed4593-7276-4dd3-866c-9f553e2f1e0a)

As for the actual issue, I don't plan on adding any more examples, as I don't maintain this module anymore and the websocket API changes too often for me to keep track. If you have a follow up question, feel free to respond, even if the issue is closed, but I think you should be able to figure things out by continue to dig down into the rabbit hole.

Good luck!

**Closed as completed by kakaroto** 2024-06-10 23:42 UTC

**Comment by S-North** [comment] 2024-06-11 09:24
Thanks for the clarification. 
I was interested in this as a way to interact programatically with Foundry for a character sheet app i.e. like DDB android app for Foundry.
But the fact that this is using the undocumented private api that changes without warning, its probably a bad idea for me to try and buid anything on top of this. I understand why you stopped supporting this project and take it as a warning :)
I hope one day Foundry will provide a way of accessing the javascript API from 3rd party apps.
